export const CRYPTO_DEPOSIT_CREATED = "CRYPTO_DEPOSIT_CREATED";
export const CRYPTO_DEPOSIT_UPDATED = "CRYPTO_DEPOSIT_UPDATED";
export const CRYPTO_DEPOSIT_CANCELLED = "CRYPTO_DEPOSIT_CANCELLED";
export const FLIP_NOTABLE_DROP = "FLIP NOTABLE DROP";
export const FLIP_CREATOR = "FLIP CREATOR";
